org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.vfs.watch=false

mod_version=1.0.0
mod_id=actionassist
mod_name=Action Assist
maven_group=io.github.brainage04.actionassist
archives_base_name=actionassist
loader_version=0.19.3
architectury_loom_version=1.17.491
fabric_loom_version=1.16.3
fabricmoddingconventions_version=2.4.7
