modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description="Configurable client-side automation for repeated use, attack, sneaking, companion keys, and hotbar transfers."
authors="brainage04"
displayURL="https://github.com/brainage04/ActionAssist"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="CLIENT"

[[mixins]]
config="actionassist.mixins.json"
